### ISSUE TITLE
Always getting this error

### ISSUE THREAD

**Issue by CloudPower97** [ssivanatarajan/stylelint-group-selectors#1]
Hi there,
I've followed the Installation and Usage in the readme but this plugin just won't work for me.
That's the error I always get: 

`Error: Cannot find module 'md5'     at Function.Module._resolveFilename (module.js:543:15)     at Function.Module._load (module.js:473:25)     at Module.require (module.js:586:17)     at require (internal/module.js:11:18)     at Object.<anonymous> (/home/claudio/Documents/Educabile/educabile-web/node_modules/stylelint-group-selectors/index.js:2:11)     at Object.<anonymous> (/home/claudio/Documents/Educabile/educabile-web/node_modules/stylelint-group-selectors/index.js:68:3)     at Module._compile (module.js:642:30)     at Object.Module._extensions..js (module.js:653:10)     at Module.load (module.js:561:32)     at tryModuleLoad (module.js:504:12)`

Can you please tell what is going wrong?

**Comment by ssivanatarajan** [comment]
Hi @CloudPower97, Fixed the issue. Could you please check now?

**Comment by CloudPower97** [comment]
I'm sorry but I keep getting the same exact error :(

**Comment by ssivanatarajan** [comment]
Have you reinstalled the package?

**Comment by CloudPower97** [comment]
Yes, as matter of fact I have this in my `package.json  "stylelint-group-selectors": "^1.0.6"

**Comment by ssivanatarajan** [comment]
@CloudPower97 , Sorry for the inconvenience, now fixed the issue. could you reinstall the package?

**Comment by CloudPower97** [comment]
Everything works fine now, thank you :+1:
